display_name: Strix
package_name: strix
maintainer:
  name: strix
  email: linux@strix.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/source/ic_launcher_border.png

postinstall_scripts:
  - echo "Installed Strix"
postuninstall_scripts:
  - echo "Surprised Why?"

keywords:
  - Strix
  - Proxy
  - VPN
  - V2ray
  - Nekoray
  - Xray
  - Psiphon
  - OpenVPN

generic_name: Strix

categories:
  - Network

startup_notify: true
