app_id: 6L903538-42B1-4596-G479-BJ779F21A65D
publisher: Strix
publisher_url: ""
display_name: Strix
executable_name: Strix.exe
output_base_file_name: Strix.exe
create_desktop_icon: true
install_dir_name: "{autopf64}\\Strix"
setup_icon_file: ..\..\windows\runner\resources\app_icon.ico
locales:
  - ar
  - en
  - fa
  - ru
  - pt
  - tr
script_template: inno_setup.sas
